create table app_users (
    id bigint generated by default as identity primary key,
    login varchar(64) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp with time zone not null default current_timestamp
);

create table user_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    session_id uuid not null unique,
    active boolean not null,
    created_at timestamp with time zone not null default current_timestamp,
    invalidated_at timestamp with time zone
);

create index idx_user_sessions_user_active
    on user_sessions(user_id, active);

create table media_assets (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references app_users(id) on delete cascade,
    uuid uuid not null unique,
    media_type varchar(16) not null,
    processing_status varchar(32) not null,
    analysis_status varchar(32) not null,
    original_filename varchar(512) not null,
    mime_type varchar(255) not null,
    size_bytes bigint not null,
    uploaded_at timestamp with time zone not null default current_timestamp
);

create index idx_media_assets_owner_uploaded
    on media_assets(owner_id, uploaded_at desc);

create table media_variants (
    id bigint generated by default as identity primary key,
    asset_id bigint not null references media_assets(id) on delete cascade,
    variant_type varchar(32) not null,
    bucket_name varchar(255) not null,
    object_key varchar(1024) not null,
    content_type varchar(255) not null,
    size_bytes bigint not null,
    created_at timestamp with time zone not null default current_timestamp,
    constraint uq_media_variant unique (asset_id, variant_type)
);

create table media_metadata (
    id bigint generated by default as identity primary key,
    asset_id bigint not null unique references media_assets(id) on delete cascade,
    width_px integer,
    height_px integer,
    taken_at timestamp with time zone,
    camera_make varchar(255),
    camera_model varchar(255),
    device_name varchar(255),
    latitude double precision,
    longitude double precision,
    orientation varchar(64)
);

create table media_tags (
    id bigint generated by default as identity primary key,
    asset_id bigint not null references media_assets(id) on delete cascade,
    tag_value varchar(255) not null,
    tag_source varchar(32) not null,
    confidence double precision,
    created_at timestamp with time zone not null default current_timestamp
);

create index idx_media_tags_asset
    on media_tags(asset_id);

create index idx_media_tags_value
    on media_tags(tag_value);
