alter table media_assets
    add column recognized_text text;

alter table media_assets
    add column recognized_text_normalized text;

create table media_processing_jobs (
    id bigint generated by default as identity primary key,
    asset_id bigint not null unique references media_assets(id) on delete cascade,
    status varchar(32) not null,
    attempts integer not null default 0,
    available_at timestamp with time zone not null default current_timestamp,
    last_error text,
    created_at timestamp with time zone not null default current_timestamp,
    started_at timestamp with time zone,
    completed_at timestamp with time zone
);

create index idx_media_processing_jobs_status_available
    on media_processing_jobs(status, available_at);
