alter table media_assets
    add column checksum_sha256 varchar(64);

create table media_delivery_requests (
    id bigint generated by default as identity primary key,
    asset_id bigint not null references media_assets(id) on delete cascade,
    owner_id bigint not null references app_users(id) on delete cascade,
    variant_type varchar(32) not null,
    status varchar(32) not null,
    checksum_sha256 varchar(64),
    acknowledged_checksum_sha256 varchar(64),
    last_error text,
    download_attempts integer not null default 0,
    created_at timestamp with time zone not null default current_timestamp,
    delivered_at timestamp with time zone
);

create index idx_media_delivery_requests_owner_created
    on media_delivery_requests(owner_id, created_at desc);
